name: Build and Push to GHCR

on:
  push:
    branches: [main]
    tags: ['v*']

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Build binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -o app .

      - uses: ko-build/setup-ko@v0.6

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          ko login ghcr.io \
            --username ${{ github.actor }} \
            --password-stdin

      - name: Build & Push Image
        run: |
          export KO_DOCKER_REPO=ghcr.io/${{ github.repository_owner }}

          SHORT_SHA=${GITHUB_SHA::7}
          TAGS="${SHORT_SHA}"

          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            TAGS="${TAGS},${GITHUB_REF_NAME}"
          fi

          TAGS="${TAGS},latest"
          echo "tags is ${TAGS}"

          IMAGE=`ko build . --base-import-paths --tags ${TAGS}`

          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "DIGEST=${IMAGE#*@}" >> $GITHUB_ENV

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: joekyo/shiny-octo-argo
          token: ${{ secrets.GH_PAT }}
          path: argo

      - name: Update image digest
        run: |
          cd argo
          yq -i '
            (.images[] | select(.name=="miniweb") | .digest) = strenv(DIGEST)
          ' k8s/overlays/prod/kustomization.yaml

      - name: Commit changes
        run: |
          cd argo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "deploy miniweb ${{ steps.ko.outputs.image }}" || echo "no changes"
          git push
