name: Build and Push to GHCR

on:
  push:
    branches: [main]
    tags: ['v*']

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Build binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
          go build -o app .

      - uses: ko-build/setup-ko@v0.6

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          ko login ghcr.io \
            --username ${{ github.actor }} \
            --password-stdin

      - name: Build & Push Image
        run: |
          export KO_DOCKER_REPO=ghcr.io/${{ github.repository_owner }}

          SHORT_SHA=${GITHUB_SHA::7}
          TAGS="${SHORT_SHA}"

          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            TAGS="${TAGS},${GITHUB_REF_NAME}"
          fi

          TAGS="${TAGS},latest"
          echo "tags is ${TAGS}"

          ko build . --base-import-paths --tags ${TAGS}
